CREATE TABLE products_import (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date DATE,
  product_name VARCHAR(100),
  color VARCHAR(50),
  amount DECIMAL(10, 4),
  unit VARCHAR(20),
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blacklisted_tokens (
        id INT AUTO_INCREMENT PRIMARY KEY,
        jti VARCHAR(255) NOT NULL UNIQUE,
        expires_at DATETIME NOT NULL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);